### ISSUE TITLE
Notes on the proposal

### ISSUE THREAD

**Issue by roman-kulish** [romshark/Go-2-Proposal---Immutability#6]
Some of the problems outlined in this proposal can be fixed by-design.
### Immutable struct fields
```go
type Object struct {
	ImmutableField const *Object // Immutable
	MutableField   *Object       // Mutable
}
```
-- vs --
```go
type Object struct {
	immutableField *Object // Immutable, private visibility
	MutableField   *Object   // Mutable
}

// ImmutableField is an accessor method of the Object receiver
func (o Object) ImmutableField() *Object {
    return o.immutableField
}
```
### Immutable methods
```go
// ImmutableMethod is a const method.
func (o const *Object) ImmutableMethod() const *Object {
    o.MutatingMethod()         // Compile-time error
    o.mutableField = &Object{} // Compile-time error
    return o.mutableField
}
```
-- vs --

```go
// ImmutableMethod is a const method, the receiver is a copy of a value, NOT the reference.
func (o Object) ImmutableMethod() Object {
    o.MutatingMethod()         // Compile-time error
    o.mutableField = &Object{} // Compile-time error
    return o.mutableField
}
```
### Immutable functions
```go
// ImmutableMethod is a const method
func (o const *Object) ImmutableMethod() {}
```
-- vs --
```go
// ImmutableMethod is a const method, the argument is a copy of a value, NOT the reference.
func (o Object) ImmutableMethod() {}
```
### Note on constants
> Constants in Go are just that—constant. They are created at compile time, even when defined as locals in functions, and can only be numbers, characters (runes), strings or booleans. Because of the compile-time restriction, the expressions that define them must be constant expressions, evaluatable by the compiler. For instance, 1<<3 is a constant expression, while math.Sin(math.Pi/4) is not because the function call to math.Sin needs to happen at run time.

https://golang.org/doc/effective_go.html#constants

Because constants are created at compile time it may require a significant language change, impose limitations or lead to unexpected behaviour such as: 
* when invoking a function which may mutate the immutable receiver
```go
type Object struct {
	ImmutableField *Object // Immutable, private visibility
	MutableField   *Object   // Mutable
}

func (o const *Object) Func1() *Object {
    return o.Func2()
}

func (o *Object) Func2() {
    o.ImmutableField = 22 // what os "o", is it a "const" receiver?
}
```
* compiler may not be able to find the size required to fit immutable type, if that type has dynamic fields like maps, slices or strings.
* how this should work with slices:
```go
type ImmutableSlice const []int

a:= ImmutableSlice{1, 2, 3}
b:= a[1:]
b = append(b, 4, 5, 6)
```
* how this should work with embedding?
```go
type Object1 struct {
	Field string
}

type Object2 struct {
        Object1 // how to enforce embedded object Field property to be a const?
}

func (o *Object1) Func() {
	// what if I need o.Field immutable here?
}
```
* if two objects implement the same interface, but I want object to be immutable and the other one mutable?
```go
type Blaher interface {
	Blah() *Object
}

type Object1 struct {}
type Object2 struct {}

func(Object1) Blah() const *Object {} // isn't it a violation of the method return declared in the interface ?
func (Object2) Blah() *Object {}

```
* I don't think that the compiler can capture all the possible ways you can mutate variables in go and so runtime should also do some checks, which may affect performance.

**Comment by romshark** [comment]
### RE: Immutable struct fields
I've described why we need immutable struct fields right here: https://github.com/romshark/Go-2-Proposal---Immutability/pull/3#discussion_r214764431 in full detail, please check it out.

### RE: Immutable methods
The _copying_ part is exactly what we want to get rid of with this proposal. Having to copy a large struct every time you call it's method is painfully slow so you'll have to make the exclusive choice: safety vs performance. 

Though this is not the biggest problem, the worst problem is that you can still mutate your "copy" if it includes reference type fields:

```go
type Object struct {
	parent   *Object
	children []*Object
}

// MutatingMethod mutates the object
type (o *Object) MutatingMethod() {
	/*...*/
}

// SeeminglyImmutableMethod only seems to be immutable,
// in reality though it's pretty insidious still allowing
// you to mutate the internals of the seemingly immutable
// receiver, which is very dangerous!
func (o Object) SeeminglyImmutableMethod() {
	// We can mutate the parent field
	o.parent.MutatingMethod()

	// We can eve mutate the list of children
	o.children[5] = nil
}
```

With immutable methods though, not only do we safe us the unnecessary copy, we can also avoid mutating the object for real:

```go
// MutateObject mutates the given object
func MutateObject(obj *Object) {
	obj.MutatingMethod()
}

// ActuallyImmutableMethod is guaranteed by the compiler
// to not change any internals of the object including references
func (o const *Object) ActuallyImmutableMethod() {
	// All fields of "o" are contextually immutably
	// in the scope of this function

	// We can't call methods with mutable receiver
	// on a contextually immutable field
	o.parent.MutatingMethod() // Compile-time error

	// We can't assign to a contextually immutable field
	o.children[5] = nil // Compile-time error

	// We can't use type "const *Object" as "*Object"
	MutateObject(o) // Compile-time error
}
```

### RE: Immutable functions
Not sure what you mean. Those are just methods that we just discussed.

### RE: Note on constants
When were're talking about the use of the keyword `const` for immutable variables / fields / receivers / return values and argument, we're talking about _overloading_ this keyword for immutability, not about actual constants.

**Immutables are not constants**! An immutable slice is not a constant slice, it's just an immutable reference to a mutable array. Immutables don't make memory read only, they rather protect memory from undesired mutations in certain contexts by other human beings. They make the compiler cut the developer's fingers off if they try to mutate a certain symbol that's not supposed to be mutated in a particular context. Consider this:

```go
func GenerateRandom(n int) (const []int, []int) {
	newSlice := make([]int, n)
	for i := 0; i < n; i++ {
		newSlice[i] = randomInt()
	}
	return newSlice, newSlice
}

func main() {
	immutableList, mutableList := GenerateRandom(10)

	// The immutable reference protects the underlying array
	immutableList[5] = 42 // Compile-time error

	// Let's mutate the underlying array through a mutable reference
	mutableList[5] = 42

	// Now we can observe the mutation on an immutable reference
	x := immutableList[5] // = 42
}
```

...And **no**, you should do the above code, if you want to make the slice immutable in **all contexts**, you must throw the mutable `newSlice` reference away as soon as `GenerateRandom` returns.

> compiler may not be able to find the size required to fit immutable type, if that type has dynamic fields like maps, slices or strings.
Immutable maps, slices and strings are just like regular maps, slices and strings except that they're write-protected within certain contexts.
So there won't be any problem determining their size because it's the same as the size of regular ones.

----

> how could this work with slices?
I'm currently elaborating the slice aliasing issue. Basically sub-slices will inherit their slice's type, thus a sub-slice of an immutable slice is also immutable:

```
type Object struct {
	children []*Object
}

func (o const *Object) GetSubSlice() []*Object {
	// Cannot use contextually immutable sub-slice as mutable slice
	return o.children[1:2] // Compile-time error
}
```

----

> if two objects implement the same interface, but I want object to be immutable and the other one mutable?

I'm currently still thinking about immutable interfaces, though I suppose that the interfaces must then define what methods must be mutable and which must be immutable:
```
interface Log {
	Write(const []byte)
	const Read() const []byte
}
```
This means, that an implementation of such an interface must look like this:
```
type MyLog struct {}

// Write implements the mutable Writer.Write method
func (ml *MyLog) Write(data const []byte) {
	// ...
}

// Read implements the immutable Writer.Read method
func (ml const *MyLog) Read() const []byte {
	// ...
}
```
Though this is not yet part of the proposal because I'm not quite sure about it yet, but it most probably will be added that way.

---

> I don't think that the compiler can capture all the possible ways you can mutate variables in go and so runtime should also do some checks, which may affect performance.

we need concrete examples where the compiler would not be able to protect immutable variables from being mutated to address those problems. If you have any ideas in what exact cases this could happen then please share your thoughts. So far I can't think of why we'd need runtime-enforced immutability.

**Comment by romshark** [comment]
I consider this issue resolved. If you still have any thoughts left for discussion then please consider opening new issues for each particular topic, thanks!
