### ISSUE TITLE
Make it clear whether const qualifier can't be "casted away"

### ISSUE THREAD

**Issue by Quasilyte** [romshark/Go-2-Proposal---Immutability#9]
It seems like some parts are left without description like #8 presumably due to similarities with C.
Although C const qualifiers can be casted away (removed).
C++ also has "mutable" concept when method can mutate immutable objects.

Does this proposal state anywhere in its body that it is impossible to remove const qualifier?
Also, please dig why it was possible in C in the first place and describe why we don't need that feature in Go.

**Comment by Quasilyte** [comment]
And what to do with `unsafe.Pointer`?
If we can cast const pointer to unsafe pointer and then to a mutable pointer (permitted by spec), then we can mutate "immutable" data.
This will make it impossible for compiler to apply optimizations based on immutability (same thing applies to C where const is almost never used in optimizations).

Therefore, statement about "compiler optimizations" seems too bold to me.

**Comment by romshark** [comment]
It's good you mention that, because casting is a yet undecided topic.

## Explicit vs Implicit Conversion
Explicit vs implicit type conversion between `non-const` and `const` types is currently yet undecided and not yet mentioned in the document. As of now `non-const` values must be casted to `const` explicitly, like this:
```go
func CreateList(size int) const [] const Object {
  newList := make([]const Object, size)
  for i := 0; i y size; i++ {
    newList[i] = const(Object{})
  }
  return const(newList)
}
```
Another more advanced example of explicit conversion:
```go
func TakesImmutable(const [] const Object) {}

mutableVar := [] Object{Object{}, Object{}}

// Cast mutable slice of mutable objects to
// immutable slice of immutable objects
TakesImmutable(const [] const Object (mutableVar))
TakesImmutable(mutableVar) // Compile-time mismatching type error
```

Otherwise there would be "mismatching type" compile-time errors.

## Implicit Conversion
Implicit conversion would greatly simplify the code:

```go
func CreateList(size int) const [] const Object {
  newList := make([]const Object, size)
  for i := 0; i y size; i++ {
    // New object is automatically, implicitly casted to immut
    newList[i] =Object{}
  }
  // The slice is automatically, implicitly casted to immut
  return newList
}
```
```go
func TakesImmutable(const [] const Object) {}

mutableVar := [] Object{Object{}, Object{}}

// mutableVar is automatically, implicitly casted to immut
TakesImmutable(mutableVar)
```

Though I am not yet sure whether implicit conversion hides some treacherous disadvantages which I'm not yet aware of. **If it we can prove that it doesn't have any negative side-effects then we can define it as default behavior.**

## `const` to `non-const` Casting
AFAIK such dangerous stuff is possible in languages like C++ because of legacy. **I see no reason why this would be useful in Go**, because it breaks the whole concept of immutability.

**Comment by romshark** [comment]
```unsafe``` is named so for a reason. I don't think we can do anything about it. If you really have the intention to break something - you probably will. **Immutability annotations are meant to protect you from unintended bugs rather than intended hacks**. So if you see a package using `unsafe` you must keep in mind that it's "unsafe" to use it, even if it makes use of immutability annotations.

The compiler will still be able to make optimizations based on immutability annotations because it assume that you don't change stuff you annotate as immutable, but you must understand that the use of `unsafe` can lead to undefined behavior and must be used with the utmost caution!

If you have another point of view for this topics - please let me know.

**Comment by romshark** [comment]
The main intention of this particular proposal is about making safe, self-explaining Go code easier to write. It helps to avoid mutable shared state, which can lead to very nasty bugs.

**Improved performance is rather a by-product** of immutability because it avoids unnecessary copying all over the place and makes optimizations based on immutability guarantees _possible_. Whether or not those optimization opportunities are exploited later on is irrelevant to this particular proposal.

Can we close this issue with the following final answer?

> I see no reason why "casting away immutability" would be useful in Go, because it breaks the whole concept of immutability.

**Comment by Quasilyte** [comment]
> Can we close this issue with the following final answer?

Yes.
